<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemsSeeder extends Seeder {
  /**
   * Run the database seeds.
   */
  public function run(): void {
    $items = array(
      array(
        "code" => "7150",
        "name" => "CER BANANA  ZERO ACUC 3X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "241",
        "name" => "DOCE LIGHT ABACAXI 380G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "242",
        "name" => "DOCE LIGHT FIGO 380G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "243",
        "name" => "DOCE LIGHT MORANGO 380G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "245",
        "name" => "DOCE LIGHT GOIABA 380G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "249",
        "name" => "DOCE LIGHT UVA 380G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "282",
        "name" => "DOCE ABOBORA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "283",
        "name" => "DOCE BANANA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "284",
        "name" => "DOCE GOIABA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "287",
        "name" => "DOCE FIGO 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "289",
        "name" => "DOCE UVA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "290",
        "name" => "DOCE MORANGO 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "382",
        "name" => "DOCE ABOBORA/COCO BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "391",
        "name" => "DOCE ABACAXI BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "393",
        "name" => "DOCE BANANA BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "395",
        "name" => "DOCE GOIABA BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "396",
        "name" => "DOCE LARANJA BLD 5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "399",
        "name" => "DOCE DE UVA BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "405",
        "name" => "DOCE FIGO BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "491",
        "name" => "DOCE MORANGO BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "492",
        "name" => "DOCE AMORA BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "495",
        "name" => "DOCE PESSEGO BLD 4,5KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "620",
        "name" => "CREME DE AVELÃ COM CACAU 250G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "642",
        "name" => "CREME DE AVELÃ COM CACAU 550G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "646",
        "name" => "CREME DE AVELÃ COM CACAU 1,05KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 6,
      ),
      array(
        "code" => "647",
        "name" => "CREME DE AVELÃ COM CACAU 3KG",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "648",
        "name" => "CREME DE AVELA ZERO ACUCAR 150G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "644",
        "name" => "CREME DE CHOCOLATE 250G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "643",
        "name" => "CREME DE AMENDOIM 250g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "645",
        "name" => "CREME DE AMENDOIM C/CACAU 250G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "360",
        "name" => "GEL GOURMET CERVEJA IPA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "361",
        "name" => "GEL  GOURMET CERVEJA STOUT 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "374",
        "name" => "GEL  GOURMET DAMASCO COM PIMENTA 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "376",
        "name" => "GEL  GOURMET ALHO 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "378",
        "name" => "GEL  GOURMET CEBOLA CARAMELIZADA 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "351",
        "name" => "GEL ABACAXI COM GENGIBRE 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "355",
        "name" => "GEL HORTELA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "357",
        "name" => "GEL PIMENTA VERMELHA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "589",
        "name" => "GEL 1919 BLUEBERRY 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "590",
        "name" => "GEL 1919 FRUTAS VERMELHAS 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "591",
        "name" => "GEL 1919 ABACAXI 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "592",
        "name" => "GEL 1919 AMORA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "593",
        "name" => "GEL 1919 FRAMBOESA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "594",
        "name" => "GEL 1919 MORANGO 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "595",
        "name" => "GEL LARANJA C/CASQUINHA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "596",
        "name" => "GEL 1919 FIGO 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "597",
        "name" => "GEL 1919 GOIABA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "598",
        "name" => "GEL 1919 PESSEGO 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "599",
        "name" => "GEL 1919 UVA 310g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "711",
        "name" => "GEL 1919 LIGHT ABACAXI 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "712",
        "name" => "GEL 1919 LIGHT FRAMBOESA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "713",
        "name" => "GEL 1919 LIGHT GOIABA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "714",
        "name" => "GEL 1919 LIGHT MACA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "715",
        "name" => "GEL 1919 LIGHT MORANGO 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "716",
        "name" => "GEL 1919 LIGHT UVA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "717",
        "name" => "GEL 1919 LIGHT PESSEGO 260G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "719",
        "name" => "GEL 1919 LIGHT FRUTAS VER 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "441",
        "name" => "GEL ABACAXI 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "442",
        "name" => "GEL AMORA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "445",
        "name" => "GEL FRAMBOESA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "448",
        "name" => "GEL MACA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "449",
        "name" => "GEL MORANGO 400G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "451",
        "name" => "GEL PESSEGO 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "459",
        "name" => "GEL UVA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "861",
        "name" => "GEL DIET ABACAXI 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "862",
        "name" => "GEL DIET AMORA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "863",
        "name" => "GEL DIET GOIABA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "864",
        "name" => "GEL DIET LARANJA 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "865",
        "name" => "GEL DIET FRAMBOESA 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "866",
        "name" => "GEL DIET MORANGO 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "868",
        "name" => "GEL DIET PESSEGO 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "869",
        "name" => "GEL DIET UVA 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "871",
        "name" => "GEL 100% FRUTAS VERMELHAS 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "872",
        "name" => "GEL 100% FR DAMASCO E PESSEGO 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "876",
        "name" => "Geleia de Morango 100% Fruta 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "877",
        "name" => "Geleia de Amora 100% Fruta 290g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "878",
        "name" => "Geleia de Blueberry (Mirtilo) 100% Fruta 290g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "853",
        "name" => "GEL ZERO AÇÚCAR GOIABA 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "856",
        "name" => "GEL ZERO AÇÚCAR MORANGO 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "858",
        "name" => "GEL ZERO AÇÚCAR PESSEGO 260g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "859",
        "name" => "Geleia de Figo Zero 260g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "400",
        "name" => "GEL MORANGO CX.140X15G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "520",
        "name" => "GEL DIET SORTIDAS CX.140X15G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "530",
        "name" => "GEL SORTIDAS CX.140X15G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "930",
        "name" => "MEL CX.140X15G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "517",
        "name" => "GEL LIGHT SORTIDAS BJ.6X15G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "519",
        "name" => "GEL SORTIDAS BJ.6X15G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "7511",
        "name" => "Display Banana c/chocolate 24x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7521",
        "name" => "Display Coco c/chocolate 24x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7811",
        "name" => "Conjunto Banana c/chocolate 3x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "7821",
        "name" => "Conjunto Coco c/chocolate 3x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "7919",
        "name" => "Caixa Banana c/chocolate 144x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7929",
        "name" => "Caixa Coco c/chocolate 144x20g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "5011",
        "name" => "CEREAL AVEIA E AVELA  RITTER 24X20G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "5012",
        "name" => "CEREAL AVEIA E BRIGADEIRO RITTER 24X20G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "5013",
        "name" => "CEREAL AVEIA E MORANGO RITTER 24X20G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "5015",
        "name" => "CEREAL AVEIA E BANANA RITTER 24X20G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "2205",
        "name" => "CER BAR BANANA LIGHT 24X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "2255",
        "name" => "CER BAR BROWNIE LIGHT C/CHOC 24X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "2236",
        "name" => "CER BAR MORANGO LIGHT C/CHOC 24X25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7605",
        "name" => "Banana Aveia e Mel  24x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7617",
        "name" => "Castanha do Pará 24x22g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7946",
        "name" => "Morango C/ Choc Branco 24x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7666",
        "name" => "Brownie C/ Choc Branco 24x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7640",
        "name" => "Avelã Cast. c/Choc 24x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7606",
        "name" => "Banana c/Choc  24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7635",
        "name" => "Brigadeiro 24x22g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7590",
        "name" => "Brownie Choc  24x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7600",
        "name" => "Capuccino  24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7730",
        "name" => "Frutas vermelhas c/chocolate 24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7936",
        "name" => "Morango c/Chocolate  24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7550",
        "name" => "Sobremesa de Limão c/Choc    24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7570",
        "name" => "Cer.Bar.Zero  Brigadeiro 24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7560",
        "name" => "Cer.Bar.Zero  Morango c/ch 24x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7571",
        "name" => "CEREAL BROWNIE C/CHOC ZERO 24X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "7655",
        "name" => "Cer.Bar.Zero  Banana 24x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "2105",
        "name" => "CER BAR BANANA LIGHT 3X25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "2155",
        "name" => "CER BAR BROWNIE LIGHT CHOC 3X25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "2136",
        "name" => "CER BAR MORANGO LIGHT C/CHOC 3X25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7105",
        "name" => "Banana Aveia e Mel 3x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7017",
        "name" => "Castanha do Pará 3x22g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7446",
        "name" => "Morango C/ Choc Branco 3x20g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7166",
        "name" => "Brownie C/ Choc Branco 3x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7140",
        "name" => "Avelã Cast. c/Choc  3x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7155",
        "name" => "Banana c/Choc 3x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7136",
        "name" => "Brigadeiro 3x22g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7055",
        "name" => "Brownie Choc  3x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7065",
        "name" => "Capuccino  3x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7130",
        "name" => "Frutas vermelhas c/chocolate  3x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7436",
        "name" => "Morango c/Chocolate  3x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7035",
        "name" => "Sobremesa de Limão c/Choc 3x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "9105",
        "name" => "CEREAL DE BANANA, AVEIA E MEL Leve 4 pague 3\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "9140",
        "name" => "Avelã Cast. c/Choc Leve 4 pague 3",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "9136",
        "name" => "CEREAL EM BARRA SABOR BRIGADEIRO Leve 4 pague 3\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7137",
        "name" => "Cer.Bar.Zero  Brigadeiro 3x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7336",
        "name" => "Cer.Bar.Zero  Morango c/ch 3x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7138",
        "name" => "CEREAL BROWNIE C/CHOC ZERO 3X25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "5071",
        "name" => "CEREAL AVEIA E AVELA RITTER LV4PG3\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "5072",
        "name" => "CEREAL AVEIA E BRIGADEIRO RITTER LV4PG3\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "5073",
        "name" => "CEREAL AVEIA E MORANGO RITTER LV4PG3",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "5075",
        "name" => "CEREAL AVEIA BANANA RITTER  LV4PG3\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "5051",
        "name" => "CEREAL AVEIA E AVELA RITTER 144X20G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "5052",
        "name" => "CEREAL AVEIA E BRIGADEIRO RITTER 144X20G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "5053",
        "name" => "CEREAL AVEIA E MORANGO RITTER 144X20G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "5055",
        "name" => "CEREAL AVEIA E BANANA RITTER 144X20G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "2305",
        "name" => "CER BAR BANANA LIGHT 144X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "2355",
        "name" => "CER BAR BROWNIE LIGHT C/CHOC 144X25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "2336",
        "name" => "CER BAR MORANGO LIGHT C/CHOC 144X25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7608",
        "name" => "Banana Aveia e Mel   144x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7717",
        "name" => "Castanha do Pará 144x22g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7948",
        "name" => "Morango C/ Choc Branco 144x20g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7766",
        "name" => "Brownie C/ Choc Branco 144x20g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7748",
        "name" => "Avelã Cast. c/Choc  144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7708",
        "name" => "Banana c/Choc  144x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7638",
        "name" => "Brigadeiro 144x22g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7578",
        "name" => "Brownie Choc  144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7588",
        "name" => "Capuccino  144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7738",
        "name" => "Frutas vermelhas c/chocolate 144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7938",
        "name" => "CER BAR MORANGO CHOC 144x25G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7558",
        "name" => "Sobremesa de Limão c/Choc 144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7678",
        "name" => "Cer.Bar.Zero  Brigadeiro 144x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7679",
        "name" => "CAIXA 144 UND CEREAL BROWNIE C/CHOC ZERO 25G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7528",
        "name" => "Cer.Bar.Zero  Morango c/ch 144x25g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7858",
        "name" => "Cer.Bar.Zero  Banana 144x25g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "8301",
        "name" => "BARRA NUTS MORANGO E CRANBERRY 12X30G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "8302",
        "name" => "BARRA NUTS SEMENTES 12X30G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "8303",
        "name" => "BARRA NUTS BANANA 12X30G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "8201",
        "name" => "BARRA NUTS MORANGO E CRANBERRY  2X30G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "8202",
        "name" => "BARRA NUTS SEMENTES GRÃOS ANCESTRAIS  2X30G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "8203",
        "name" => "BARRA NUTS BANANA 2X30G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "7795",
        "name" => "BARRA PROTEINA CHOCOLATE C/COB CHOC 12X33g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "7742",
        "name" => "BARRA PROTEINA MORANGO COM CHOC 12X33g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "7195",
        "name" => "BARRA PROTEINA CHOCOLATE COM CHOC 3X33g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7142",
        "name" => "BARRA PROTEINA MORANGO COM CHOC 3X33g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 36,
      ),
      array(
        "code" => "7695",
        "name" => "BARRA PROTEINA CHOCOLATE COM CHOC 120X33g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7642",
        "name" => "BARRA PROTEINA MORANGO COM CHOC 120X33g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "7685",
        "name" => "BARRA PROTEINA BAUNILHA COM CHOC 120X33g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 1,
      ),
      array(
        "code" => "8401",
        "name" => "BARRA FRUTA AMEIXA & COCO 24X28g",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "8406",
        "name" => "BARRA FRUTA CACAU & FRUTAS 24X30g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "8451",
        "name" => "BARRA FRUTA AMEIXA & COCO 2X28g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "8456",
        "name" => "BARRA FRUTA CACAU & FRUTAS 2X30g\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 24,
      ),
      array(
        "code" => "3710",
        "name" => "MIX FRUTAS SECAS 30G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 28,
      ),
      array(
        "code" => "3711",
        "name" => "MIX BERRY 30G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 28,
      ),
      array(
        "code" => "3713",
        "name" => "MIX AMENDOIM 30G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 28,
      ),
      array(
        "code" => "6641",
        "name" => "GRANOLA TOP GRAIN ZERO SACHE 220G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "6643",
        "name" => "GRANOLA TOP GRAIN CACAU E NIBS ZERO SACHE 220G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 8,
      ),
      array(
        "code" => "6647",
        "name" => "GRANOLA, AVEIA E CACAU SACHE 250G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "6648",
        "name" => "GRANOLA, AVEIA E FRUTAS SACHE 250G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "6649",
        "name" => "GRANOLA TOP GRAIN SACHE 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 6,
      ),
      array(
        "code" => "281",
        "name" => "DOCE ABACAXI 400G\n",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "443",
        "name" => "GEL GOIABA 400G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 12,
      ),
      array(
        "code" => "651",
        "name" => "CREME DE AVELÃ DISPLAY 50X10G",
        "client_id" => 2,
        "creation_user" => 33,
        "amount" => 4,
      ),
      array(
        "code" => "471",
        "name" => "GELEIA ABACAXI BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "472",
        "name" => "GELEIA AMORA BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "473",
        "name" => "GELEIA ALHO CARAMELIZADO BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "474",
        "name" => "GELEIA CEBOLA CARAMELIZADA BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "475",
        "name" => "GELEIA FRUTAS VERMELHAS BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "476",
        "name" => "GELEIA GOIABA BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "477",
        "name" => "GELEIA PIMENTA BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "478",
        "name" => "GELEIA MORANGO BLD 1,2KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "375",
        "name" => "GEL GOURMET MORANGO C/ PIMENTA 290G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "857",
        "name" => "GEL ZERO AÇÚCAR PIMENTA 260G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "854",
        "name" => "GEL ZERO AÇÚCAR FRUTAS VERMELHAS 260G 290G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "373",
        "name" => "GEL GOURMET GOIABA COM LARANJA 290G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "377",
        "name" => "GEL GOURMET MAÇÃ CARAMELIZADA 290G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "855",
        "name" => "GEL ZERO AÇÚCAR CEBOLA CARAMELIZADA 260G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "LA7017",
        "name" => "CER BAR CASTANHA DO PARA CX15 3X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA7055",
        "name" => "CER BAR BROWNIE CHOC CX15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA7105",
        "name" => "CER BAR BANANA AVEIA E MEL CX15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA7137",
        "name" => "CER BRIGADEIRO ZERO ACUC CX15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA7166",
        "name" => "CER BAR BROWNIE C/ CHOC BRANCO CX15 3X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA7436",
        "name" => "CER BAR MORANGO C/ CHOC CX15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8545",
        "name" => "BARRA FRUTA COCO C/ CHOC LEVEN 3X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8552",
        "name" => "BARRA PROTEINA CHOCOLATE C/ CHOC LEVEN 12X33G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "LA8501",
        "name" => "CER BAR BANANA LEVEN CX15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8502",
        "name" => "CER BAR MORANGO C/ CHOC LEVEN 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8503",
        "name" => "CER BAR TORTA DE LIMAO C/ CHOC LEVEN 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8504",
        "name" => "CER BAR PETIT GATEAU CHOC LEVEN 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8505",
        "name" => "CER BAR PETIT GATEAU C/ CHOC BRANCO LEVEN 3X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8506",
        "name" => "CER BAR AVELA C/ CHOC LEVEN 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8507",
        "name" => "BAR NUTS BANANA LEVEN 2X30G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8508",
        "name" => "BAR NUTS MORANGO CRAMBERRY LEVEN 2X30G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "LA8509",
        "name" => "BAR NUTS SEMENTES LEVEN 2X30G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8531",
        "name" => "BAR AVEIA   ABACAXI C/ COCO LEVEN 24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8532",
        "name" => "BAR AVEIA   LARANJA C/ CHOC LEVEN 24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8533",
        "name" => "BAR AVEIA   FRUTAS VERMELHAS LEVEN 24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8534",
        "name" => "BAR AVEIA   IORGURTE DE MORANGO LEVEN 24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8544",
        "name" => "BARRA FRUTA BANANA C/ CHOC LEVEN 3X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8542",
        "name" => "BARRA FRUTA BAN/CHOC LEVEN CX 8 DP24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8543",
        "name" => "BARRA FRUTA COCO C/ CHOC LEVEN CX 8 DP24X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "8553",
        "name" => "BAR PROTEINA MORANGO C/ CHOC LEVEN DP 12X33G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 12,
      ),
      array(
        "code" => "LA7150",
        "name" => "CER BANANA ZERO ACUC CX 15 3X25G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7505",
        "name" => "CER BAR MAÇA C/ CANELA 3X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 36,
      ),
      array(
        "code" => "7501",
        "name" => "CER BAR CARAMELO SALGADO C/ AMEND E CHOC ZERO 3X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 36,
      ),
      array(
        "code" => "7502",
        "name" => "CER BAR MOCACCINO ZERO 3X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 36,
      ),
      array(
        "code" => "7504",
        "name" => "CER BAR MORANGO COB BRANCA ZERO 3X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 36,
      ),
      array(
        "code" => "8704",
        "name" => "CER BAR MAÇA C/ CANELA 144X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7576",
        "name" => "CER BAR MAÇA C/ CANELA 24X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8702",
        "name" => "CER BAR MOCACCINO ZERO 144X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7573",
        "name" => "CER BAR CARAMELO SALGADO C/ AMEND E CHOC ZERO 24X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8701",
        "name" => "CER BAR CAR SALG C/ AMEN E COB BRA ZERO 144X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7574",
        "name" => "CER BAR MOCACCINO ZERO 24X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "8703",
        "name" => "CER BAR MORANGO COB BRANCA ZERO144X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7575",
        "name" => "CER BAR MORANGO COB BRANCA ZERO 24X22G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 8,
      ),
      array(
        "code" => "650",
        "name" => "CREME DE AVELA ZERO ACUCAR 3KG",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 4,
      ),
      array(
        "code" => "LA7811",
        "name" => "BARRA FRUTA BANANA C/CHOC CX12 3X20G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 1,
      ),
      array(
        "code" => "7794",
        "name" => "MAXI SPORT WHEY PROT BAR MORANGO 12X40G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 6,
      ),
      array(
        "code" => "7796",
        "name" => "MAXI SPORT WHEY PROT BAR BROWNIE 12X40G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 6,
      ),
      array(
        "code" => "7797",
        "name" => "MAXI SPORT WHEY PROT BAR BEIJINHO 12X40G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 6,
      ),
      array(
        "code" => "7798",
        "name" => "MAXI SPORT WHEY PROT BAR TORTA LIMAO 12X40G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 6,
      ),
      array(
        "code" => "7799",
        "name" => "MAXI SPORT WHEY PROT BAR NAPOLITANO 12X40G",
        "client_id" => 2,
        "creation_user" => 39,
        "amount" => 6,
      ),
    );

    Item::insert($items);
  }
}
