<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
//Models
use App\Models\ProfilePermission;

class ProfilePermissionsSeeder extends Seeder {
  public function run(): void {
    $profile_permissions = [
      [
        'id' => 1,
        'profile_id' => 1,
        'sidebar_id' => 1,
        'client_id' => 1,
        'affiliate_id' => 1,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-06-18 20:37:45',
        'updated_at' => '2024-06-18 20:37:45',
      ],
      [
        'id' => 2,
        'profile_id' => 2,
        'sidebar_id' => 1,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-06-18 20:37:45',
        'updated_at' => '2024-06-18 20:37:45',
      ],
      [
        'id' => 3,
        'profile_id' => 2,
        'sidebar_id' => 2,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-06-18 20:37:45',
        'updated_at' => '2024-06-18 20:37:45',
      ],
      [
        'id' => 4,
        'profile_id' => 2,
        'sidebar_id' => 6,
        'client_id' => 1,
        'affiliate_id' => 28,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-06-18 20:37:45',
        'updated_at' => '2024-06-18 20:37:45',
      ],
      [
        'id' => 5,
        'profile_id' => 2,
        'sidebar_id' => 28,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-06-18 20:37:45',
        'updated_at' => '2024-06-18 20:37:45',
      ],
      [
        'id' => 6,
        'profile_id' => 2,
        'sidebar_id' => 3,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:15:37',
        'updated_at' => '2024-07-22 22:15:37',
      ],
      [
        'id' => 7,
        'profile_id' => 2,
        'sidebar_id' => 4,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:15:50',
        'updated_at' => '2024-07-22 22:15:50',
      ],
      [
        'id' => 8,
        'profile_id' => 2,
        'sidebar_id' => 5,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:16:01',
        'updated_at' => '2024-07-22 22:16:01',
      ],
      [
        'id' => 9,
        'profile_id' => 2,
        'sidebar_id' => 7,
        'client_id' => 1,
        'affiliate_id' => 7,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:17:12',
        'updated_at' => '2024-07-22 22:17:12',
      ],
      [
        'id' => 10,
        'profile_id' => 2,
        'sidebar_id' => 8,
        'client_id' => 1,
        'affiliate_id' => 7,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:17:12',
        'updated_at' => '2024-07-22 22:17:12',
      ],
      [
        'id' => 11,
        'profile_id' => 2,
        'sidebar_id' => 9,
        'client_id' => 1,
        'affiliate_id' => 7,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:17:24',
        'updated_at' => '2024-07-22 22:17:24',
      ],
      [
        'id' => 12,
        'profile_id' => 2,
        'sidebar_id' => 30,
        'client_id' => 1,
        'affiliate_id' => 7,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:17:34',
        'updated_at' => '2024-07-22 22:17:34',
      ],
      [
        'id' => 13,
        'profile_id' => 2,
        'sidebar_id' => 29,
        'client_id' => 1,
        'affiliate_id' => 28,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-07-22 22:18:11',
        'updated_at' => '2024-07-22 22:18:11',
      ],
      [
        'id' => 14,
        'profile_id' => 2,
        'sidebar_id' => 31,
        'client_id' => 1,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-08-27 11:45:33',
        'updated_at' => '2024-08-27 11:45:33',
      ],
      [
        'id' => 16,
        'profile_id' => 2,
        'sidebar_id' => 33,
        'client_id' => 1,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-08-31 20:27:17',
        'updated_at' => '2024-08-31 20:27:17',
      ],
      [
        'id' => 17,
        'profile_id' => 3,
        'sidebar_id' => 1,
        'client_id' => 2,
        'affiliate_id' => 1,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-02 15:22:51',
        'updated_at' => '2024-09-02 15:22:51',
      ],
      [
        'id' => 18,
        'profile_id' => 4,
        'sidebar_id' => 1,
        'client_id' => 2,
        'affiliate_id' => 1,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-02 15:22:51',
        'updated_at' => '2024-09-02 15:22:51',
      ],
      [
        'id' => 19,
        'profile_id' => 4,
        'sidebar_id' => 2,
        'client_id' => 2,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-02 15:22:51',
        'updated_at' => '2024-09-02 15:22:51',
      ],
      [
        'id' => 20,
        'profile_id' => 4,
        'sidebar_id' => 28,
        'client_id' => 2,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-02 15:22:51',
        'updated_at' => '2024-09-02 15:22:51',
      ],
      [
        'id' => 21,
        'profile_id' => 4,
        'sidebar_id' => 6,
        'client_id' => 2,
        'affiliate_id' => 28,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-02 15:22:51',
        'updated_at' => '2024-09-02 15:22:51',
      ],
      [
        'id' => 22,
        'profile_id' => 4,
        'sidebar_id' => 3,
        'client_id' => 2,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-03 13:22:20',
        'updated_at' => '2024-09-03 13:22:20',
      ],
      [
        'id' => 23,
        'profile_id' => 4,
        'sidebar_id' => 5,
        'client_id' => 2,
        'affiliate_id' => 2,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-03 13:22:31',
        'updated_at' => '2024-09-03 13:22:31',
      ],
      [
        'id' => 24,
        'profile_id' => 4,
        'sidebar_id' => 32,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-03 13:22:45',
        'updated_at' => '2024-09-11 11:58:26',
      ],
      [
        'id' => 26,
        'profile_id' => 5,
        'sidebar_id' => 1,
        'client_id' => 2,
        'affiliate_id' => 1,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-03 13:55:53',
        'updated_at' => '2024-09-03 13:55:53',
      ],
      [
        'id' => 27,
        'profile_id' => 4,
        'sidebar_id' => 29,
        'client_id' => 2,
        'affiliate_id' => 28,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-03 18:56:00',
        'updated_at' => '2024-09-03 18:56:00',
      ],
      [
        'id' => 28,
        'profile_id' => 4,
        'sidebar_id' => 34,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-09 21:55:24',
        'updated_at' => '2024-09-11 11:58:26',
      ],
      [
        'id' => 29,
        'profile_id' => 4,
        'sidebar_id' => 35,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-09 21:55:39',
        'updated_at' => '2024-09-11 11:58:34',
      ],
      [
        'id' => 30,
        'profile_id' => 5,
        'sidebar_id' => 33,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-09 21:58:54',
        'updated_at' => '2024-09-11 11:58:19',
      ],
      [
        'id' => 31,
        'profile_id' => 5,
        'sidebar_id' => 32,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 0,
        'update' => 0,
        'delete' => 0,
        'description' => null,
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-11 11:34:32',
        'updated_at' => '2024-09-11 11:34:32',
      ],
      [
        'id' => 32,
        'profile_id' => 4,
        'sidebar_id' => 33,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-09-23 19:25:33',
        'updated_at' => '2024-10-10 14:30:41',
      ],
      [
        'id' => 33,
        'profile_id' => 4,
        'sidebar_id' => 36,
        'client_id' => 2,
        'affiliate_id' => 32,
        'view' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
        'description' => '',
        'creation_user' => 1,
        'situation' => 1,
        'created_at' => '2024-10-10 14:38:23',
        'updated_at' => '2024-10-10 14:38:23',
      ],
    ];

    ProfilePermission::insert($profile_permissions);
  }
}
