<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
//Models
use App\Models\ProfilePermission;

class ProfilePermissionsSeeder extends Seeder {
  public function run(): void {
    $profile_permissions = $profile_permissions = array(
      array(
        "profile_id" => 1,
        "sidebar_id" => 1,
        "client_id" => 1,
        "affiliate_id" => 1,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-06-18 20:37:45",
        "updated_at" => "2024-06-18 20:37:45",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 1,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-06-18 20:37:45",
        "updated_at" => "2024-06-18 20:37:45",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 2,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-06-18 20:37:45",
        "updated_at" => "2024-06-18 20:37:45",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 6,
        "client_id" => 1,
        "affiliate_id" => 28,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-06-18 20:37:45",
        "updated_at" => "2024-06-18 20:37:45",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 28,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-06-18 20:37:45",
        "updated_at" => "2024-06-18 20:37:45",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 3,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:15:37",
        "updated_at" => "2024-07-22 22:15:37",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 4,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:15:50",
        "updated_at" => "2024-07-22 22:15:50",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 5,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:16:01",
        "updated_at" => "2024-07-22 22:16:01",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 7,
        "client_id" => 1,
        "affiliate_id" => 7,
        "view" => 1,
        "create" => 0,
        "update" => 0,
        "delete" => 0,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:17:12",
        "updated_at" => "2024-07-22 22:17:12",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 8,
        "client_id" => 1,
        "affiliate_id" => 7,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:17:12",
        "updated_at" => "2024-07-22 22:17:12",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 9,
        "client_id" => 1,
        "affiliate_id" => 7,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:17:24",
        "updated_at" => "2024-07-22 22:17:24",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 30,
        "client_id" => 1,
        "affiliate_id" => 7,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:17:34",
        "updated_at" => "2024-07-22 22:17:34",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 29,
        "client_id" => 1,
        "affiliate_id" => 28,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-07-22 22:18:11",
        "updated_at" => "2024-07-22 22:18:11",
      ),
      array(
        "profile_id" => 2,
        "sidebar_id" => 31,
        "client_id" => 1,
        "affiliate_id" => 2,
        "view" => 1,
        "create" => 1,
        "update" => 1,
        "delete" => 1,
        "description" => NULL,
        "creation_user" => 1,
        "situation" => 1,
        "created_at" => "2024-08-27 11:45:33",
        "updated_at" => "2024-08-27 11:45:33",
      ),
    );

    ProfilePermission::insert($profile_permissions);
  }
}
