<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// Models
use App\Models\Sidebar;

class SidebarsSeeder extends Seeder {
  public function run(): void {
    $sidebars = array(
      array(
        "name" => "Inicio",
        "icon" => "menu-icon tf-icons bx bx-home-circle",
        "slug" => "homepage",
        "affiliate_id" => 0,
        "url" => "/",
        "client_id" => "0",
        "order" => 1,
        "created_at" => "2024-05-22 18:34:35",
        "updated_at" => "2024-05-22 18:34:35",
      ),
      array(
        "name" => "Sistema",
        "icon" => "bx bx-cog me-2",
        "slug" => "sys",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "0",
        "order" => 2,
        "created_at" => "2024-05-22 18:53:47",
        "updated_at" => "2024-05-22 18:53:47",
      ),
      array(
        "name" => "Usuários",
        "icon" => NULL,
        "slug" => "user",
        "affiliate_id" => 2,
        "url" => "/users",
        "client_id" => "0",
        "order" => 1,
        "created_at" => "2024-05-22 18:56:26",
        "updated_at" => "2024-05-22 18:56:26",
      ),
      array(
        "name" => "Clientes",
        "icon" => NULL,
        "slug" => "client",
        "affiliate_id" => 2,
        "url" => "/clients",
        "client_id" => "0",
        "order" => 2,
        "created_at" => "2024-05-22 19:08:16",
        "updated_at" => "2024-05-22 19:08:16",
      ),
      array(
        "name" => "Perfis",
        "icon" => NULL,
        "slug" => "profile",
        "affiliate_id" => 2,
        "url" => "/profiles",
        "client_id" => "0",
        "order" => 3,
        "created_at" => "2024-05-22 19:19:02",
        "updated_at" => "2024-05-22 19:19:02",
      ),
      array(
        "name" => "Permissões",
        "icon" => NULL,
        "slug" => "permission",
        "affiliate_id" => 2,
        "url" => "/profile/permissions",
        "client_id" => "0",
        "order" => 4,
        "created_at" => "2024-05-22 19:24:20",
        "updated_at" => "2024-05-22 19:24:22",
      ),
      array(
        "name" => "Suporte",
        "icon" => "menu-icon tf-icons bx bx-support",
        "slug" => "sup",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "0",
        "order" => 5,
        "created_at" => "2024-05-23 19:55:42",
        "updated_at" => "2024-05-23 19:55:42",
      ),
      array(
        "name" => "Roadmap",
        "icon" => NULL,
        "slug" => "roadmap",
        "affiliate_id" => 7,
        "url" => "/task/roadmap",
        "client_id" => "0",
        "order" => 2,
        "created_at" => "2024-05-23 19:56:11",
        "updated_at" => "2024-05-23 19:56:11",
      ),
      array(
        "name" => "Chamados",
        "icon" => NULL,
        "slug" => "task",
        "affiliate_id" => 7,
        "url" => "/tasks",
        "client_id" => "0",
        "order" => 1,
        "created_at" => "2024-05-27 16:27:17",
        "updated_at" => "2024-05-27 16:27:17",
      ),
      array(
        "name" => "Estrutura",
        "icon" => "menu-icon bx bx-sitemap",
        "slug" => "structure",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "0",
        "order" => 3,
        "created_at" => "2024-06-03 11:39:09",
        "updated_at" => "2024-06-03 11:39:09",
      ),
      array(
        "name" => "Safras",
        "icon" => NULL,
        "slug" => "harvest",
        "affiliate_id" => 10,
        "url" => "/harvests",
        "client_id" => "0",
        "order" => 1,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
      array(
        "name" => "Organizações",
        "icon" => NULL,
        "slug" => "organization",
        "affiliate_id" => 10,
        "url" => "/organizations",
        "client_id" => "0",
        "order" => 2,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
      array(
        "name" => "Culturas",
        "icon" => NULL,
        "slug" => "culture",
        "affiliate_id" => 10,
        "url" => "/cultures",
        "client_id" => "0",
        "order" => 3,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
      array(
        "name" => "Cultivo",
        "icon" => "menu-icon bx bx-leaf",
        "slug" => "cultive",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "0",
        "order" => 4,
        "created_at" => "2024-06-03 11:39:09",
        "updated_at" => "2024-06-03 11:39:09",
      ),
      array(
        "name" => "Métodos",
        "icon" => NULL,
        "slug" => "method",
        "affiliate_id" => 14,
        "url" => "/cultive/methods",
        "client_id" => "0",
        "order" => 1,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
      array(
        "name" => "Hora Máquinas",
        "icon" => NULL,
        "slug" => "machine-hour",
        "affiliate_id" => 14,
        "url" => "/cultive/machine-hours",
        "client_id" => "0",
        "order" => 2,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
      array(
        "name" => "Processo/Etapas",
        "icon" => NULL,
        "slug" => "process",
        "affiliate_id" => 14,
        "url" => "/cultive/processes",
        "client_id" => "0",
        "order" => 3,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
      ),
    );

    Sidebar::insert($sidebars);
  }
}
