<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// Models
use App\Models\Sidebar;

class SidebarsSeeder extends Seeder {
  public function run(): void {
    $sidebars = array(
      array(
        "name" => "Inicio",
        "icon" => "menu-icon tf-icons bx bx-home-circle",
        "slug" => "homepage",
        "affiliate_id" => 0,
        "url" => "/",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-05-22 18:34:35",
        "updated_at" => "2024-05-22 18:34:35",
        "visibility" => 1,
      ),
      array(
        "name" => "Sistema",
        "icon" => "menu-icon bx bx-cog me-2",
        "slug" => "sys",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-05-22 18:53:47",
        "updated_at" => "2024-05-22 18:53:47",
        "visibility" => 1,
      ),
      array(
        "name" => "Usuários",
        "icon" => NULL,
        "slug" => "user",
        "affiliate_id" => 2,
        "url" => "/sys/users",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-05-22 18:56:26",
        "updated_at" => "2024-05-22 18:56:26",
        "visibility" => 1,
      ),
      array(
        "name" => "Clientes",
        "icon" => NULL,
        "slug" => "client",
        "affiliate_id" => 2,
        "url" => "/sys/clients",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-05-22 19:08:16",
        "updated_at" => "2024-05-22 19:08:16",
        "visibility" => 1,
      ),
      array(
        "name" => "Perfis",
        "icon" => NULL,
        "slug" => "profile",
        "affiliate_id" => 2,
        "url" => "/sys/profiles",
        "client_id" => "1,2",
        "order" => 3,
        "created_at" => "2024-05-22 19:19:02",
        "updated_at" => "2024-05-22 19:19:02",
        "visibility" => 1,
      ),
      array(
        "name" => "Permissões",
        "icon" => NULL,
        "slug" => "permission",
        "affiliate_id" => 28,
        "url" => "/sys/p-permissions",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-05-22 19:24:20",
        "updated_at" => "2024-05-22 19:24:22",
        "visibility" => 1,
      ),
      array(
        "name" => "Suporte",
        "icon" => "menu-icon tf-icons bx bx-support",
        "slug" => "sup",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "1,2",
        "order" => 6,
        "created_at" => "2024-05-23 19:55:42",
        "updated_at" => "2024-05-23 19:55:42",
        "visibility" => 1,
      ),
      array(
        "name" => "Roadmap",
        "icon" => NULL,
        "slug" => "roadmap",
        "affiliate_id" => 7,
        "url" => "/support/task-roadmap",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-05-23 19:56:11",
        "updated_at" => "2024-05-23 19:56:11",
        "visibility" => 1,
      ),
      array(
        "name" => "Chamados",
        "icon" => NULL,
        "slug" => "task",
        "affiliate_id" => 7,
        "url" => "/support/tasks",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-05-27 16:27:17",
        "updated_at" => "2024-05-27 16:27:17",
        "visibility" => 1,
      ),
      array(
        "name" => "Estrutura",
        "icon" => "menu-icon bx bx-sitemap",
        "slug" => "structure",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "1,2",
        "order" => 3,
        "created_at" => "2024-06-03 11:39:09",
        "updated_at" => "2024-06-03 11:39:09",
        "visibility" => 1,
      ),
      array(
        "name" => "Safras",
        "icon" => NULL,
        "slug" => "harvest",
        "affiliate_id" => 25,
        "url" => "/harvest/harvests",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Organizações",
        "icon" => NULL,
        "slug" => "organization",
        "affiliate_id" => 10,
        "url" => "/structure/organizations",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Culturas",
        "icon" => NULL,
        "slug" => "culture",
        "affiliate_id" => 14,
        "url" => "/cultive/cultures",
        "client_id" => "1,2",
        "order" => 4,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Cultivo",
        "icon" => "menu-icon bx bx-leaf",
        "slug" => "cultive",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "1,2",
        "order" => 4,
        "created_at" => "2024-06-03 11:39:09",
        "updated_at" => "2024-06-03 11:39:09",
        "visibility" => 1,
      ),
      array(
        "name" => "Métodos",
        "icon" => NULL,
        "slug" => "method",
        "affiliate_id" => 14,
        "url" => "/cultive/methods",
        "client_id" => "1,2",
        "order" => 5,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Hora máquinas",
        "icon" => NULL,
        "slug" => "machine-hour",
        "affiliate_id" => 14,
        "url" => "/cultive/machine-hours",
        "client_id" => "1,2",
        "order" => 6,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Processo/Etapas",
        "icon" => NULL,
        "slug" => "process",
        "affiliate_id" => 14,
        "url" => "/cultive/processes",
        "client_id" => "1,2",
        "order" => 3,
        "created_at" => "2024-06-03 11:42:15",
        "updated_at" => "2024-06-03 11:42:15",
        "visibility" => 1,
      ),
      array(
        "name" => "Localidades",
        "icon" => NULL,
        "slug" => "localit",
        "affiliate_id" => 10,
        "url" => "/structure/localities",
        "client_id" => "1,2",
        "order" => 6,
        "created_at" => "2024-06-04 15:32:36",
        "updated_at" => "2024-06-04 15:32:36",
        "visibility" => 1,
      ),
      array(
        "name" => "Fazendas",
        "icon" => NULL,
        "slug" => "farm",
        "affiliate_id" => 10,
        "url" => "/structure/farms",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-06-04 15:32:36",
        "updated_at" => "2024-06-04 15:32:36",
        "visibility" => 1,
      ),
      array(
        "name" => "Talhões",
        "icon" => NULL,
        "slug" => "field",
        "affiliate_id" => 10,
        "url" => "/structure/fields",
        "client_id" => "1,2",
        "order" => 4,
        "created_at" => "2024-06-04 15:32:36",
        "updated_at" => "2024-06-04 15:32:36",
        "visibility" => 1,
      ),
      array(
        "name" => "Setores",
        "icon" => NULL,
        "slug" => "sector",
        "affiliate_id" => 10,
        "url" => "/structure/sectors",
        "client_id" => "1,2",
        "order" => 3,
        "created_at" => "2024-06-04 15:32:36",
        "updated_at" => "2024-06-04 15:32:36",
        "visibility" => 1,
      ),
      array(
        "name" => "Secções",
        "icon" => NULL,
        "slug" => "section",
        "affiliate_id" => 10,
        "url" => "/structure/sections",
        "client_id" => "1,2",
        "order" => 5,
        "created_at" => "2024-06-04 15:32:36",
        "updated_at" => "2024-06-04 15:32:36",
        "visibility" => 1,
      ),
      array(
        "name" => "Grupos",
        "icon" => NULL,
        "slug" => "group",
        "affiliate_id" => 14,
        "url" => "/cultive/groups",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-06-04 15:38:39",
        "updated_at" => "2024-06-04 15:38:39",
        "visibility" => 1,
      ),
      array(
        "name" => "Variedades",
        "icon" => NULL,
        "slug" => "variet",
        "affiliate_id" => 14,
        "url" => "/cultive/varieties",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-06-04 15:38:39",
        "updated_at" => "2024-06-04 15:38:39",
        "visibility" => 1,
      ),
      array(
        "name" => "Safra",
        "icon" => " menu-icon bx bx-calendar",
        "slug" => "harv",
        "affiliate_id" => 0,
        "url" => "",
        "client_id" => "1,2",
        "order" => 5,
        "created_at" => "2024-06-04 15:38:39",
        "updated_at" => "2024-06-04 15:38:39",
        "visibility" => 1,
      ),
      array(
        "name" => "Configuração safras",
        "icon" => NULL,
        "slug" => "configuration",
        "affiliate_id" => 25,
        "url" => "/harvest/harvest-configurations",
        "client_id" => "1,2",
        "order" => 1,
        "created_at" => "2024-06-04 15:38:39",
        "updated_at" => "2024-06-04 15:38:39",
        "visibility" => 1,
      ),
      array(
        "name" => "Fechamento",
        "icon" => NULL,
        "slug" => "closure",
        "affiliate_id" => 28,
        "url" => "/sys/closure-modules",
        "client_id" => "1,2",
        "order" => 4,
        "created_at" => "2024-05-22 18:56:26",
        "updated_at" => "2024-05-22 18:56:26",
        "visibility" => 1,
      ),
      array(
        "name" => "Segurança",
        "icon" => "menu-icon tf-icons bx bx-support",
        "slug" => "sys-sec",
        "affiliate_id" => 2,
        "url" => "",
        "client_id" => "1,2",
        "order" => 5,
        "created_at" => "2024-05-22 19:24:20",
        "updated_at" => "2024-05-22 19:24:22",
        "visibility" => 1,
      ),
      array(
        "name" => "Perfis de usuário",
        "icon" => NULL,
        "slug" => "u-p",
        "affiliate_id" => 28,
        "url" => "/sys/u-profiles",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-05-22 19:24:20",
        "updated_at" => "2024-05-22 19:24:22",
        "visibility" => 1,
      ),
      array(
        "name" => "Comentários chamado",
        "icon" => NULL,
        "slug" => "comment",
        "affiliate_id" => 7,
        "url" => "/support/task-comments",
        "client_id" => "1,2",
        "order" => 2,
        "created_at" => "2024-05-23 19:56:11",
        "updated_at" => "2024-05-23 19:56:11",
        "visibility" => 0,
      ),
    );

    Sidebar::insert($sidebars);
  }
}
