<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// Models
use App\Models\Sidebar;

class SidebarsSeeder extends Seeder {
  public function run(): void {
    $sidebars = [
      [
        'id' => 1,
        'name' => 'Inicio',
        'icon' => 'menu-icon bx bx-home-circle',
        'slug' => 'homepage',
        'affiliate_id' => 0,
        'url' => '/',
        'client_id' => '1,2',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-05-22 18:34:35',
        'updated_at' => '2024-09-02 15:22:59',
      ],
      [
        'id' => 2,
        'name' => 'Sistema',
        'icon' => 'menu-icon bx bx-cog me-2',
        'slug' => 'sys',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '1,2',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-05-22 18:53:47',
        'updated_at' => '2024-09-02 15:23:05',
      ],
      [
        'id' => 3,
        'name' => 'Usuários',
        'icon' => null,
        'slug' => 'user',
        'affiliate_id' => 2,
        'url' => '/sys/users',
        'client_id' => '1,2',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-05-22 18:56:26',
        'updated_at' => '2024-09-02 15:23:11',
      ],
      [
        'id' => 4,
        'name' => 'Clientes',
        'icon' => null,
        'slug' => 'client',
        'affiliate_id' => 2,
        'url' => '/sys/clients',
        'client_id' => '1',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-05-22 19:08:16',
        'updated_at' => '2024-05-22 19:08:16',
      ],
      [
        'id' => 5,
        'name' => 'Perfis',
        'icon' => null,
        'slug' => 'profile',
        'affiliate_id' => 2,
        'url' => '/sys/profiles',
        'client_id' => '1,2',
        'order' => 3,
        'visibility' => 1,
        'created_at' => '2024-05-22 19:19:02',
        'updated_at' => '2024-09-02 15:23:26',
      ],
      [
        'id' => 6,
        'name' => 'Permissões',
        'icon' => null,
        'slug' => 'permission',
        'affiliate_id' => 28,
        'url' => '/sys/p-permissions',
        'client_id' => '1,2',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-05-22 19:24:20',
        'updated_at' => '2024-09-02 15:23:31',
      ],
      [
        'id' => 7,
        'name' => 'Suporte',
        'icon' => 'menu-icon bx bx-support',
        'slug' => 'sup',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '1',
        'order' => 6,
        'visibility' => 1,
        'created_at' => '2024-05-23 19:55:42',
        'updated_at' => '2024-05-23 19:55:42',
      ],
      [
        'id' => 8,
        'name' => 'Roadmap',
        'icon' => null,
        'slug' => 'roadmap',
        'affiliate_id' => 7,
        'url' => '/support/task-roadmap',
        'client_id' => '1',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-05-23 19:56:11',
        'updated_at' => '2024-05-23 19:56:11',
      ],
      [
        'id' => 9,
        'name' => 'Chamados',
        'icon' => null,
        'slug' => 'task',
        'affiliate_id' => 7,
        'url' => '/support/tasks',
        'client_id' => '1',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-05-27 16:27:17',
        'updated_at' => '2024-05-27 16:27:17',
      ],
      [
        'id' => 10,
        'name' => 'Estrutura',
        'icon' => 'menu-icon bx bx-sitemap',
        'slug' => 'structure',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '1',
        'order' => 3,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:39:09',
        'updated_at' => '2024-06-03 11:39:09',
      ],
      [
        'id' => 11,
        'name' => 'Safras',
        'icon' => null,
        'slug' => 'harvest',
        'affiliate_id' => 25,
        'url' => '/harvest/harvests',
        'client_id' => '1',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 12,
        'name' => 'Organizações',
        'icon' => null,
        'slug' => 'organization',
        'affiliate_id' => 10,
        'url' => '/structure/organizations',
        'client_id' => '1',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 13,
        'name' => 'Culturas',
        'icon' => null,
        'slug' => 'culture',
        'affiliate_id' => 14,
        'url' => '/cultive/cultures',
        'client_id' => '1',
        'order' => 4,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 14,
        'name' => 'Cultivo',
        'icon' => 'menu-icon bx bx-leaf',
        'slug' => 'cultive',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '1',
        'order' => 4,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:39:09',
        'updated_at' => '2024-06-03 11:39:09',
      ],
      [
        'id' => 15,
        'name' => 'Métodos',
        'icon' => null,
        'slug' => 'method',
        'affiliate_id' => 14,
        'url' => '/cultive/methods',
        'client_id' => '1',
        'order' => 5,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 16,
        'name' => 'Hora máquinas',
        'icon' => null,
        'slug' => 'machine-hour',
        'affiliate_id' => 14,
        'url' => '/cultive/machine-hours',
        'client_id' => '1',
        'order' => 6,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 17,
        'name' => 'Processo/Etapas',
        'icon' => null,
        'slug' => 'process',
        'affiliate_id' => 14,
        'url' => '/cultive/processes',
        'client_id' => '1',
        'order' => 3,
        'visibility' => 1,
        'created_at' => '2024-06-03 11:42:15',
        'updated_at' => '2024-06-03 11:42:15',
      ],
      [
        'id' => 18,
        'name' => 'Localidades',
        'icon' => null,
        'slug' => 'localit',
        'affiliate_id' => 10,
        'url' => '/structure/localities',
        'client_id' => '1',
        'order' => 6,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:32:36',
        'updated_at' => '2024-06-04 15:32:36',
      ],
      [
        'id' => 19,
        'name' => 'Fazendas',
        'icon' => null,
        'slug' => 'farm',
        'affiliate_id' => 10,
        'url' => '/structure/farms',
        'client_id' => '1',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:32:36',
        'updated_at' => '2024-06-04 15:32:36',
      ],
      [
        'id' => 20,
        'name' => 'Talhões',
        'icon' => null,
        'slug' => 'field',
        'affiliate_id' => 10,
        'url' => '/structure/fields',
        'client_id' => '1',
        'order' => 4,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:32:36',
        'updated_at' => '2024-06-04 15:32:36',
      ],
      [
        'id' => 21,
        'name' => 'Setores',
        'icon' => null,
        'slug' => 'sector',
        'affiliate_id' => 10,
        'url' => '/structure/sectors',
        'client_id' => '1',
        'order' => 3,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:32:36',
        'updated_at' => '2024-06-04 15:32:36',
      ],
      [
        'id' => 22,
        'name' => 'Secções',
        'icon' => null,
        'slug' => 'section',
        'affiliate_id' => 10,
        'url' => '/structure/sections',
        'client_id' => '1',
        'order' => 5,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:32:36',
        'updated_at' => '2024-06-04 15:32:36',
      ],
      [
        'id' => 23,
        'name' => 'Grupos',
        'icon' => null,
        'slug' => 'group',
        'affiliate_id' => 14,
        'url' => '/cultive/groups',
        'client_id' => '1',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:38:39',
        'updated_at' => '2024-06-04 15:38:39',
      ],
      [
        'id' => 24,
        'name' => 'Variedades',
        'icon' => null,
        'slug' => 'variet',
        'affiliate_id' => 14,
        'url' => '/cultive/varieties',
        'client_id' => '1',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:38:39',
        'updated_at' => '2024-06-04 15:38:39',
      ],
      [
        'id' => 25,
        'name' => 'Safra',
        'icon' => ' menu-icon bx bx-calendar',
        'slug' => 'harv',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '1',
        'order' => 5,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:38:39',
        'updated_at' => '2024-06-04 15:38:39',
      ],
      [
        'id' => 26,
        'name' => 'Configuração safras',
        'icon' => null,
        'slug' => 'configuration',
        'affiliate_id' => 25,
        'url' => '/harvest/harvest-configurations',
        'client_id' => '1',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-06-04 15:38:39',
        'updated_at' => '2024-06-04 15:38:39',
      ],
      [
        'id' => 27,
        'name' => 'Fechamento',
        'icon' => null,
        'slug' => 'closure',
        'affiliate_id' => 28,
        'url' => '/sys/closure-modules',
        'client_id' => '1',
        'order' => 4,
        'visibility' => 1,
        'created_at' => '2024-05-22 18:56:26',
        'updated_at' => '2024-05-22 18:56:26',
      ],
      [
        'id' => 28,
        'name' => 'Segurança',
        'icon' => 'menu-icon bx bx-support',
        'slug' => 'sys-sec',
        'affiliate_id' => 2,
        'url' => null,
        'client_id' => '1,2',
        'order' => 5,
        'visibility' => 1,
        'created_at' => '2024-05-22 19:24:20',
        'updated_at' => '2024-09-03 13:21:56',
      ],
      [
        'id' => 29,
        'name' => 'Perfis de usuário',
        'icon' => null,
        'slug' => 'u-p',
        'affiliate_id' => 28,
        'url' => '/sys/u-profiles',
        'client_id' => '1,2',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-05-22 19:24:20',
        'updated_at' => '2024-09-03 18:55:33',
      ],
      [
        'id' => 30,
        'name' => 'Comentários chamado',
        'icon' => null,
        'slug' => 'comment',
        'affiliate_id' => 7,
        'url' => '/support/task-comments',
        'client_id' => '1',
        'order' => 2,
        'visibility' => 0,
        'created_at' => '2024-05-23 19:56:11',
        'updated_at' => '2024-05-23 19:56:11',
      ],
      [
        'id' => 31,
        'name' => 'Módulos',
        'icon' => null,
        'slug' => 'sidebar',
        'affiliate_id' => 2,
        'url' => '/sys/sidebars',
        'client_id' => '1',
        'order' => 4,
        'visibility' => 1,
        'created_at' => '2024-08-27 11:44:29',
        'updated_at' => '2024-08-27 11:44:29',
      ],
      [
        'id' => 32,
        'name' => 'Embarques',
        'icon' => 'menu-icon bx bx-package',
        'slug' => 'boar',
        'affiliate_id' => 0,
        'url' => null,
        'client_id' => '2',
        'order' => 8,
        'visibility' => 1,
        'created_at' => '2024-08-31 20:20:01',
        'updated_at' => '2024-09-02 22:42:14',
      ],
      [
        'id' => 33,
        'name' => 'Listagem',
        'icon' => null,
        'slug' => 'boardings',
        'affiliate_id' => 32,
        'url' => '/boarding/boardings',
        'client_id' => '2',
        'order' => 1,
        'visibility' => 1,
        'created_at' => '2024-08-31 20:22:31',
        'updated_at' => '2024-09-02 22:42:06',
      ],
      [
        'id' => 34,
        'name' => 'Importação',
        'icon' => null,
        'slug' => 'boar-boarding-import',
        'affiliate_id' => 32,
        'url' => '/boarding/boarding/import',
        'client_id' => '2',
        'order' => 2,
        'visibility' => 1,
        'created_at' => '2024-08-31 20:22:31',
        'updated_at' => '2024-09-02 22:42:06',
      ],
      [
        'id' => 35,
        'name' => 'Exportação',
        'icon' => null,
        'slug' => 'boar-boarding-export',
        'affiliate_id' => 32,
        'url' => '/boarding/boarding/export',
        'client_id' => '2',
        'order' => 3,
        'visibility' => 1,
        'created_at' => '2024-08-31 20:22:31',
        'updated_at' => '2024-09-02 22:42:06',
      ],
    ];

    Sidebar::insert($sidebars);
  }
}
