<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
//Models
use App\Models\User;

class UsersSeeder extends Seeder {
  public function run(): void {
    $users = [
      [
        'id' => 1,
        'name' => 'JOÃO VICTOR',
        'email' => 'joao.vdsm@outlook.com',
        'password' => '$2y$12$Owi047wuoJ88qoe5M8F.UeSeRIqEaTF5nVnLcwCe24Y/GIQURfpN2',
        'remember_token' => null,
        'in_client' => 2,
        'in_profile' => 4,
        'in_time' => '2024-09-04 22:33:00',
        'situation' => 1,
        'creation_user' => null,
        'created_at' => '2024-06-12 09:02:28',
        'updated_at' => '2024-09-04 22:33:00',
        'deleted_at' => null,
      ],
      [
        'id' => 2,
        'name' => 'MÁRCIO SCHNEIDER',
        'email' => 'marcio.schneider@synergya.com.br',
        'password' => '$2y$12$qxS.9REFSJW0t4tnjMULl.6CIOAZhMp9JYgig21UvSZAZVvUN/sFm',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 16:58:03',
        'updated_at' => '2024-09-03 16:58:03',
        'deleted_at' => null,
      ],
      [
        'id' => 3,
        'name' => 'RONALDO GARCIA',
        'email' => 'ronaldo.garcia@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 16:58:36',
        'updated_at' => '2024-09-03 16:58:36',
        'deleted_at' => null,
      ],
      [
        'id' => 4,
        'name' => 'ADRIANA PASSOS',
        'email' => 'adriana.passos@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 16:59:56',
        'updated_at' => '2024-09-03 16:59:56',
        'deleted_at' => null,
      ],
      [
        'id' => 5,
        'name' => 'RAFAEL CAMARGO',
        'email' => 'faturamento05@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:01:52',
        'updated_at' => '2024-09-03 17:01:52',
        'deleted_at' => null,
      ],
      [
        'id' => 6,
        'name' => 'ANA CAROLINA',
        'email' => 'faturamento02@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:02:34',
        'updated_at' => '2024-09-03 17:02:34',
        'deleted_at' => null,
      ],
      [
        'id' => 7,
        'name' => 'JAQUELINE PRADO',
        'email' => 'faturamento03@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:02:59',
        'updated_at' => '2024-09-03 17:02:59',
        'deleted_at' => null,
      ],
      [
        'id' => 8,
        'name' => 'ANDERSON MONTICELLI DOS REIS',
        'email' => '4420@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:03:39',
        'updated_at' => '2024-09-03 17:03:39',
        'deleted_at' => null,
      ],
      [
        'id' => 9,
        'name' => 'CHRISTIANN ESCOUTO JEUNEHOMME',
        'email' => 'exp.fat@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:04:18',
        'updated_at' => '2024-09-03 17:04:18',
        'deleted_at' => null,
      ],
      [
        'id' => 10,
        'name' => 'JOSÉ LUIZ DA SILVA GRANDO',
        'email' => '3907@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:05:07',
        'updated_at' => '2024-09-03 17:05:24',
        'deleted_at' => null,
      ],
      [
        'id' => 11,
        'name' => 'LUANA DA SILVA RODRIGUES',
        'email' => '4978@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:07:16',
        'updated_at' => '2024-09-03 17:07:16',
        'deleted_at' => null,
      ],
      [
        'id' => 12,
        'name' => 'TIAGO DA SILVA LUIZ',
        'email' => '5017@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:08:22',
        'updated_at' => '2024-09-03 17:08:22',
        'deleted_at' => null,
      ],
      [
        'id' => 13,
        'name' => 'ALFEU EDUARDO DOS SANTOS VIEIRA',
        'email' => '5089@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:12:43',
        'updated_at' => '2024-09-03 17:12:43',
        'deleted_at' => null,
      ],
      [
        'id' => 14,
        'name' => 'JOÃO LENNON RIBEIRO MACIEL DA SILVA',
        'email' => '5108@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:18:53',
        'updated_at' => '2024-09-03 17:18:53',
        'deleted_at' => null,
      ],
      [
        'id' => 15,
        'name' => 'RICARDO GABRIEL DA SILVA CAMARGO',
        'email' => '5134@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:19:36',
        'updated_at' => '2024-09-03 17:19:36',
        'deleted_at' => null,
      ],
      [
        'id' => 16,
        'name' => 'LOHAN TEIXEIRA BOURSCHEIT',
        'email' => '5107@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:20:07',
        'updated_at' => '2024-09-03 17:20:07',
        'deleted_at' => null,
      ],
      [
        'id' => 17,
        'name' => 'LUCAS GABRIEL RODRIGUES DE BORBA',
        'email' => '5149@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:20:34',
        'updated_at' => '2024-09-03 17:20:56',
        'deleted_at' => null,
      ],
      [
        'id' => 18,
        'name' => 'JUAN DAVID LIMA DE OLIVEIRA',
        'email' => '5148@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:21:26',
        'updated_at' => '2024-09-03 17:21:26',
        'deleted_at' => null,
      ],
      [
        'id' => 19,
        'name' => 'DIOGO KAUE SOARES DA LUZ',
        'email' => '5150@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:21:58',
        'updated_at' => '2024-09-03 17:21:58',
        'deleted_at' => null,
      ],
      [
        'id' => 20,
        'name' => 'RITA BORGES',
        'email' => 'faturamento04@ritteralimentos.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:22:36',
        'updated_at' => '2024-09-03 17:22:36',
        'deleted_at' => null,
      ],
      [
        'id' => 21,
        'name' => 'RUANN MOTTA LOPES',
        'email' => '5355@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => 2,
        'in_profile' => 5,
        'in_time' => '2024-09-04 22:33:48',
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:23:16',
        'updated_at' => '2024-09-04 22:33:48',
        'deleted_at' => null,
      ],
      [
        'id' => 22,
        'name' => 'VLADIMIR MACHADO DA SILVA',
        'email' => '5193@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:23:52',
        'updated_at' => '2024-09-03 17:23:52',
        'deleted_at' => null,
      ],
      [
        'id' => 23,
        'name' => 'VERA ALBANI',
        'email' => 'vera.albani@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:24:11',
        'updated_at' => '2024-09-03 21:28:08',
        'deleted_at' => null,
      ],
      [
        'id' => 24,
        'name' => 'HIAGO MINHO RODRIGUES',
        'email' => '5211@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 17:25:28',
        'updated_at' => '2024-09-03 17:25:28',
        'deleted_at' => null,
      ],
      [
        'id' => 25,
        'name' => 'ADRIAN AGUIRRE FARIAS',
        'email' => '5229@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:30:47',
        'updated_at' => '2024-09-03 21:30:47',
        'deleted_at' => null,
      ],
      [
        'id' => 26,
        'name' => 'JONATHA MIKAEL BORGES MENDONÇA',
        'email' => '5230@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:31:40',
        'updated_at' => '2024-09-03 21:31:40',
        'deleted_at' => null,
      ],
      [
        'id' => 27,
        'name' => 'GEOVANE FERREIRA DA SILVA',
        'email' => '5244@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:40:26',
        'updated_at' => '2024-09-03 21:40:26',
        'deleted_at' => null,
      ],
      [
        'id' => 28,
        'name' => 'JAIR FRANCISCO BORBA JUNIOR',
        'email' => '5251@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:41:15',
        'updated_at' => '2024-09-03 21:41:15',
        'deleted_at' => null,
      ],
      [
        'id' => 29,
        'name' => 'JAILSON PACHECO LOPES',
        'email' => '5085@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:41:52',
        'updated_at' => '2024-09-03 21:41:52',
        'deleted_at' => null,
      ],
      [
        'id' => 30,
        'name' => 'ERICK CRESPO VICENTE',
        'email' => '5272@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:42:21',
        'updated_at' => '2024-09-03 21:42:21',
        'deleted_at' => null,
      ],
      [
        'id' => 31,
        'name' => 'CLAUDIA CRISTINA BICA DA SILVA',
        'email' => '5276@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:42:46',
        'updated_at' => '2024-09-03 21:42:46',
        'deleted_at' => null,
      ],
      [
        'id' => 32,
        'name' => 'LUIS AUGUSTO RODRIGUES ROCHA',
        'email' => '5281@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:43:20',
        'updated_at' => '2024-09-03 21:43:20',
        'deleted_at' => null,
      ],
      [
        'id' => 33,
        'name' => 'LUCAS NASCIMENTO RODRIGUES',
        'email' => '5294@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:44:04',
        'updated_at' => '2024-09-03 21:44:04',
        'deleted_at' => null,
      ],
      [
        'id' => 34,
        'name' => 'CLAUDIO RENATO ALMEIDA',
        'email' => '5296@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:44:40',
        'updated_at' => '2024-09-03 21:44:40',
        'deleted_at' => null,
      ],
      [
        'id' => 35,
        'name' => 'LUCAS DA SILVA (LUCÃO)',
        'email' => '5315@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:45:06',
        'updated_at' => '2024-09-03 21:45:06',
        'deleted_at' => null,
      ],
      [
        'id' => 36,
        'name' => 'CÉZAR CRISTIANO MOREIRA SOARES',
        'email' => '5316@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:45:33',
        'updated_at' => '2024-09-03 21:45:33',
        'deleted_at' => null,
      ],
      [
        'id' => 37,
        'name' => 'CLARA DA ROSA VIEIRA',
        'email' => '5329@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:45:59',
        'updated_at' => '2024-09-03 21:45:59',
        'deleted_at' => null,
      ],
      [
        'id' => 38,
        'name' => 'JOÃO VITOR ALVES DE OLIVEIRA',
        'email' => '5350@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:46:37',
        'updated_at' => '2024-09-03 21:46:37',
        'deleted_at' => null,
      ],
      [
        'id' => 39,
        'name' => 'EDSON RODRIGUES SILVEIRA',
        'email' => '5364@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:47:06',
        'updated_at' => '2024-09-03 21:47:06',
        'deleted_at' => null,
      ],
      [
        'id' => 40,
        'name' => 'KAIRON MUNHOZ',
        'email' => '5377@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:47:26',
        'updated_at' => '2024-09-03 21:47:26',
        'deleted_at' => null,
      ],
      [
        'id' => 41,
        'name' => 'MÁRCIO FRANCISCO DE SOUZA',
        'email' => '5386@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 21:47:48',
        'updated_at' => '2024-09-03 21:47:48',
        'deleted_at' => null,
      ],
      [
        'id' => 42,
        'name' => 'GUSTAVO SCHMIDT',
        'email' => '5408@ritter.com.br',
        'password' => '$2y$12$3l0VQauiIxYk6ZZbgvUSCueGF4BwPbd3XwZYL2/RwUAUWhqfNWWVS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 22:01:43',
        'updated_at' => '2024-09-04 22:31:49',
        'deleted_at' => null,
      ],
    ];

    User::insert($users);
  }
}
