<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
//Models
use App\Models\User;

class UsersSeeder extends Seeder {
  public function run(): void {
    $users = [
      [
        'id' => 1,
        'name' => 'JOÃO VICTOR',
        'email' => 'joao.vdsm@outlook.com',
        'password' => '$2y$12$Owi047wuoJ88qoe5M8F.UeSeRIqEaTF5nVnLcwCe24Y/GIQURfpN2',
        'remember_token' => null,
        'in_client' => 2,
        'in_profile' => 4,
        'in_time' => '2024-09-03 18:55:38',
        'situation' => 1,
        'creation_user' => null,
        'created_at' => '2024-06-12 06:02:28',
        'updated_at' => '2024-09-03 18:55:38',
        'deleted_at' => null,
      ],
      [
        'id' => 2,
        'name' => 'MÁRCIO SCHNEIDER',
        'email' => 'marcio.schneider@synergya.com.br',
        'password' => '$2y$12$qxS.9REFSJW0t4tnjMULl.6CIOAZhMp9JYgig21UvSZAZVvUN/sFm',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 13:58:03',
        'updated_at' => '2024-09-03 13:58:03',
        'deleted_at' => null,
      ],
      [
        'id' => 3,
        'name' => 'RONALDO GARCIA',
        'email' => 'ronaldo.garcia@ritter.com.br',
        'password' => '$2y$12$HYtPFYsWtdDPgWU3C7Qgxen4e1F8itnbIDDY/ToEj0YWPrR3EP2iW',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 13:58:36',
        'updated_at' => '2024-09-03 13:58:36',
        'deleted_at' => null,
      ],
      [
        'id' => 4,
        'name' => 'ADRIANA PASSOS',
        'email' => 'adriana.passos@ritteralimentos.com.br',
        'password' => '$2y$12$CWMbUwZ0qHZ4EDLoabu0R.WwusbEcb3wNrGoxG0PnzqeoHlPSewdG',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 13:59:56',
        'updated_at' => '2024-09-03 13:59:56',
        'deleted_at' => null,
      ],
      [
        'id' => 5,
        'name' => 'RAFAEL CAMARGO',
        'email' => 'faturamento05@ritteralimentos.com.br',
        'password' => '$2y$12$JtM2MPNPxfGlktitQPWfbuuWIj1uhTig4olrSEyRQ0vwgYSzKoy.i',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:01:52',
        'updated_at' => '2024-09-03 14:01:52',
        'deleted_at' => null,
      ],
      [
        'id' => 6,
        'name' => 'ANA CAROLINA',
        'email' => 'faturamento02@ritteralimentos.com.br',
        'password' => '$2y$12$ipMdQ.WUmSkwGYqQYDsq9.60q7mejnmXZtZ5Lg1xlNq9fDRFKl16S',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:02:34',
        'updated_at' => '2024-09-03 14:02:34',
        'deleted_at' => null,
      ],
      [
        'id' => 7,
        'name' => 'JAQUELINE PRADO',
        'email' => 'faturamento03@ritteralimentos.com.br',
        'password' => '$2y$12$6Aki.Yi8AxbT7hMASZbhBOrigwi8smpvdpl8761TQ4Tc9CXMu1EwC',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:02:59',
        'updated_at' => '2024-09-03 14:02:59',
        'deleted_at' => null,
      ],
      [
        'id' => 8,
        'name' => 'ANDERSON MONTICELLI DOS REIS',
        'email' => '4420@ritter.com.br',
        'password' => '$2y$12$oTNIIVxsUTvU7RUImZJLTussi89K3b8yIVQQSPlRarA41EFzdRA9y',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:03:39',
        'updated_at' => '2024-09-03 14:03:39',
        'deleted_at' => null,
      ],
      [
        'id' => 9,
        'name' => 'CHRISTIANN ESCOUTO JEUNEHOMME',
        'email' => 'exp.fat@ritteralimentos.com.br',
        'password' => '$2y$12$CTfKDKPoiA2tmftxjfr84uLrAI3LW.aMp1jXglOdO72cLz.fD5uCK',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:04:18',
        'updated_at' => '2024-09-03 14:04:18',
        'deleted_at' => null,
      ],
      [
        'id' => 10,
        'name' => 'JOSÉ LUIZ DA SILVA GRANDO',
        'email' => '3907@ritter.com.br',
        'password' => '$2y$12$B3UFwJRENJwtOCZWHy4Kzu2o7yULa2Df67Rd6KMPMXhrl63/DvLTq',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:05:07',
        'updated_at' => '2024-09-03 14:05:24',
        'deleted_at' => null,
      ],
      [
        'id' => 11,
        'name' => 'LUANA DA SILVA RODRIGUES',
        'email' => '4978@ritter.com.br',
        'password' => '$2y$12$4b0ptThW818blUJ4r9ifOO.a9R121nPOCSmuAcbAm/1jCtoJcY.4.',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:07:16',
        'updated_at' => '2024-09-03 14:07:16',
        'deleted_at' => null,
      ],
      [
        'id' => 12,
        'name' => 'TIAGO DA SILVA LUIZ',
        'email' => '5017@ritter.com.br',
        'password' => '$2y$12$sHp7YngOkyp/xMCx0CHP1uPF9Qv68tR5XhGQ1ROYRyMbFjrtvTZjK',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:08:22',
        'updated_at' => '2024-09-03 14:08:22',
        'deleted_at' => null,
      ],
      [
        'id' => 13,
        'name' => 'ALFEU EDUARDO DOS SANTOS VIEIRA',
        'email' => '5089@ritter.com.br',
        'password' => '$2y$12$1Bw2swiLEHe7NTMMQqxFSuOsQgfnzVcuniqmYzu3D4001Da/Vvxm6',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:12:43',
        'updated_at' => '2024-09-03 14:12:43',
        'deleted_at' => null,
      ],
      [
        'id' => 14,
        'name' => 'JOÃO LENNON RIBEIRO MACIEL DA SILVA',
        'email' => '5108@ritter.com.br',
        'password' => '$2y$12$oA0p4dPkOypjHDVYcOxj1eTMzivY4Op/qCUOPdcpfwh2xFIkPLEm6',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:18:53',
        'updated_at' => '2024-09-03 14:18:53',
        'deleted_at' => null,
      ],
      [
        'id' => 15,
        'name' => 'RICARDO GABRIEL DA SILVA CAMARGO',
        'email' => '5134@ritter.com.br',
        'password' => '$2y$12$6l/3GBcafagAGIU7crh7Oe9bMPTHDoudgliAnJ.QqfWXeRkLSqlqO',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:19:36',
        'updated_at' => '2024-09-03 14:19:36',
        'deleted_at' => null,
      ],
      [
        'id' => 16,
        'name' => 'LOHAN TEIXEIRA BOURSCHEIT',
        'email' => '5107@ritter.com.br',
        'password' => '$2y$12$/7Px/.jHkhl3lSudcPCsVOVz8Ke23u1Fg/Ecp.mM57fHeBUN3gQF.',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:20:07',
        'updated_at' => '2024-09-03 14:20:07',
        'deleted_at' => null,
      ],
      [
        'id' => 17,
        'name' => 'LUCAS GABRIEL RODRIGUES DE BORBA',
        'email' => '5149@ritter.com.br',
        'password' => '$2y$12$dcmVE8PbHdLkJ6bVpkFDVu7OnB5D07M2ELBCZ9rN76M3KqRsg41ie',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:20:34',
        'updated_at' => '2024-09-03 14:20:56',
        'deleted_at' => null,
      ],
      [
        'id' => 18,
        'name' => 'JUAN DAVID LIMA DE OLIVEIRA',
        'email' => '5148@ritter.com.br',
        'password' => '$2y$12$KzWIj9tU0lZvCmkMuYWg.uhVKwB9sSKpgSiizkmppKOMWY4MZj.Pi',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:21:26',
        'updated_at' => '2024-09-03 14:21:26',
        'deleted_at' => null,
      ],
      [
        'id' => 19,
        'name' => 'DIOGO KAUE SOARES DA LUZ',
        'email' => '5150@ritter.com.br',
        'password' => '$2y$12$RYBovFWDM8LWjYsOyHF3CuH3pckORufHboaU3OiJ7.rUp1XtRfBa.',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:21:58',
        'updated_at' => '2024-09-03 14:21:58',
        'deleted_at' => null,
      ],
      [
        'id' => 20,
        'name' => 'RITA BORGES',
        'email' => 'faturamento04@ritteralimentos.com.br',
        'password' => '$2y$12$AuTiEC9bv33vGb06uWvO0uswDMs2ZV9PX0XIFtcrHHKiKSRJYwaNq',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:22:36',
        'updated_at' => '2024-09-03 14:22:36',
        'deleted_at' => null,
      ],
      [
        'id' => 21,
        'name' => 'RUANN MOTTA LOPES',
        'email' => '5355@ritter.com.br',
        'password' => '$2y$12$VtGS2tyvA7/UYwPwh9D8WeDkzAKw5HeYAcMAtOku6aaMJgU3GX.Oq',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:23:16',
        'updated_at' => '2024-09-03 14:23:16',
        'deleted_at' => null,
      ],
      [
        'id' => 22,
        'name' => 'VLADIMIR MACHADO DA SILVA',
        'email' => '5193@ritter.com.br',
        'password' => '$2y$12$9gp7w.XMoH/boXy92/imh.okIJbBd8sh4s9dFU1kdoBqJX6q2THGa',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:23:52',
        'updated_at' => '2024-09-03 14:23:52',
        'deleted_at' => null,
      ],
      [
        'id' => 23,
        'name' => 'VERA ALBANI',
        'email' => 'vera.albani@ritter.com.br',
        'password' => '$2y$12$XnGDVbPBKDeYNGlgEwiUSetQVyElcDh1Bmsk17CJ4YRr5uxb83Mqe',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:24:11',
        'updated_at' => '2024-09-03 18:28:08',
        'deleted_at' => null,
      ],
      [
        'id' => 24,
        'name' => 'HIAGO MINHO RODRIGUES',
        'email' => '5211@ritter.com.br',
        'password' => '$2y$12$nT3Bqb12McFE3tXExFS0m.9qGwYi9RIZ4psZ4nwmXQ3cyaqDyuWT2',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 14:25:28',
        'updated_at' => '2024-09-03 14:25:28',
        'deleted_at' => null,
      ],
      [
        'id' => 25,
        'name' => 'ADRIAN AGUIRRE FARIAS',
        'email' => '5229@ritter.com.br',
        'password' => '$2y$12$DHIuCcoOpGMSMFYMDzFucuqm/Ti3144v3dVDMSoX5QkXupCKrW74m',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:30:47',
        'updated_at' => '2024-09-03 18:30:47',
        'deleted_at' => null,
      ],
      [
        'id' => 26,
        'name' => 'JONATHA MIKAEL BORGES MENDONÇA',
        'email' => '5230@ritter.com.br',
        'password' => '$2y$12$Le/iS/Ssa7Cfqtdl13jPqOB90mfpVn1MWzRpsPy5CWzMzNxup0SDW',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:31:40',
        'updated_at' => '2024-09-03 18:31:40',
        'deleted_at' => null,
      ],
      [
        'id' => 27,
        'name' => 'GEOVANE FERREIRA DA SILVA',
        'email' => '5244@ritter.com.br',
        'password' => '$2y$12$51RJjC9Mc0hXexNFkhCM2et2GlF8Bq86cTQAQSlr8KZPbleP7PUPq',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:40:26',
        'updated_at' => '2024-09-03 18:40:26',
        'deleted_at' => null,
      ],
      [
        'id' => 28,
        'name' => 'JAIR FRANCISCO BORBA JUNIOR',
        'email' => '5251@ritter.com.br',
        'password' => '$2y$12$xRBzcOGh9MVayIgSAdvEa.P0X83gX2zaxqCoay0xKMqGzIdp55pPe',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:41:15',
        'updated_at' => '2024-09-03 18:41:15',
        'deleted_at' => null,
      ],
      [
        'id' => 29,
        'name' => 'JAILSON PACHECO LOPES',
        'email' => '5085@ritter.com.br',
        'password' => '$2y$12$6.OsobbpjVQeR7krgrsvE.6Bq4S2XccfWtfLLO3QkwcTcZlItr4mm',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:41:52',
        'updated_at' => '2024-09-03 18:41:52',
        'deleted_at' => null,
      ],
      [
        'id' => 30,
        'name' => 'ERICK CRESPO VICENTE',
        'email' => '5272@ritter.com.br',
        'password' => '$2y$12$JoO1mA5BDQRaQFgTaHMXkeuD02Rs0eXFgJSzKAmULDSTZnN6kqHmq',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:42:21',
        'updated_at' => '2024-09-03 18:42:21',
        'deleted_at' => null,
      ],
      [
        'id' => 31,
        'name' => 'CLAUDIA CRISTINA BICA DA SILVA',
        'email' => '5276@ritter.com.br',
        'password' => '$2y$12$c4SFXRMSI0itXZAPG5cRLeNmXp1frsIuD0OIGV2g2VmJ0vO8TzfY.',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:42:46',
        'updated_at' => '2024-09-03 18:42:46',
        'deleted_at' => null,
      ],
      [
        'id' => 32,
        'name' => 'LUIS AUGUSTO RODRIGUES ROCHA',
        'email' => '5281@ritter.com.br',
        'password' => '$2y$12$h2v5H1QefHtTsSK1KTazg.NWRcFWElUk4LNbNXaQpNoz6JFnyG3oG',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:43:20',
        'updated_at' => '2024-09-03 18:43:20',
        'deleted_at' => null,
      ],
      [
        'id' => 33,
        'name' => 'LUCAS NASCIMENTO RODRIGUES',
        'email' => '5294@ritter.com.br',
        'password' => '$2y$12$F2TtjW6fqyT7Y/PKV2m1uOb1mpg93aYDcrpj5PkaUofl8.b5HdPFK',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:44:04',
        'updated_at' => '2024-09-03 18:44:04',
        'deleted_at' => null,
      ],
      [
        'id' => 34,
        'name' => 'CLAUDIO RENATO ALMEIDA',
        'email' => '5296@ritter.com.br',
        'password' => '$2y$12$NpMWcaHF9it6qTZRyGzeEO/UZ.cJwYqlzD35G0pzst/CNa.q5yIm2',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:44:40',
        'updated_at' => '2024-09-03 18:44:40',
        'deleted_at' => null,
      ],
      [
        'id' => 35,
        'name' => 'LUCAS DA SILVA (LUCÃO)',
        'email' => '5315@ritter.com.br',
        'password' => '$2y$12$ptkk6DAOuqCa7vs.dTsObutaWfbrQpcTKUWe3l8fQANf8pRy0Kt.i',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:45:06',
        'updated_at' => '2024-09-03 18:45:06',
        'deleted_at' => null,
      ],
      [
        'id' => 36,
        'name' => 'CÉZAR CRISTIANO MOREIRA SOARES',
        'email' => '5316@ritter.com.br',
        'password' => '$2y$12$sQvemhGMbxJaYjxYoCfdaux6lLXN9vYbCu43spfZN27CmMIcYt3Sy',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:45:33',
        'updated_at' => '2024-09-03 18:45:33',
        'deleted_at' => null,
      ],
      [
        'id' => 37,
        'name' => 'CLARA DA ROSA VIEIRA',
        'email' => '5329@ritter.com.br',
        'password' => '$2y$12$TKPnKN1EoBV4ckIA8mhzD.ir.St7utO.qe55FlPsaytosC9zrfhom',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:45:59',
        'updated_at' => '2024-09-03 18:45:59',
        'deleted_at' => null,
      ],
      [
        'id' => 38,
        'name' => 'JOÃO VITOR ALVES DE OLIVEIRA',
        'email' => '5350@ritter.com.br',
        'password' => '$2y$12$bVdYerse0Sw1gzd2qhbXcOaOsa0aYbQcqCVmn5XthPqXR5JIR6aD.',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:46:37',
        'updated_at' => '2024-09-03 18:46:37',
        'deleted_at' => null,
      ],
      [
        'id' => 39,
        'name' => 'EDSON RODRIGUES SILVEIRA',
        'email' => '5364@ritter.com.br',
        'password' => '$2y$12$IGEOAJ4RqrKPajVc.964Ju3enPuVJfO1vPXhc65rcU2zErNkww8wm',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:47:06',
        'updated_at' => '2024-09-03 18:47:06',
        'deleted_at' => null,
      ],
      [
        'id' => 40,
        'name' => 'KAIRON MUNHOZ',
        'email' => '5377@ritter.com.br',
        'password' => '$2y$12$mrGeddGV99KnD5xv1cvUX.1IfitMpdwwAwdScbonbTpoVB6P3nO52',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:47:26',
        'updated_at' => '2024-09-03 18:47:26',
        'deleted_at' => null,
      ],
      [
        'id' => 41,
        'name' => 'MÁRCIO FRANCISCO DE SOUZA',
        'email' => '5386@ritter.com.br',
        'password' => '$2y$12$luT8HK.UAK4xC0y32NJeQ.dnyC/W7tv2VYSm7FQCK0Mn48I3xybRS',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 18:47:48',
        'updated_at' => '2024-09-03 18:47:48',
        'deleted_at' => null,
      ],
      [
        'id' => 42,
        'name' => 'GUSTAVO SCHMIDT',
        'email' => '5408@ritter.com.br',
        'password' => '$2y$12$a5nUoGWJa5rYvy9h01HKmO1bLB0652OsHnrNsgzutzPvcv0SY2oXy',
        'remember_token' => null,
        'in_client' => null,
        'in_profile' => null,
        'in_time' => null,
        'situation' => 1,
        'creation_user' => 1,
        'created_at' => '2024-09-03 19:01:43',
        'updated_at' => '2024-09-03 19:01:43',
        'deleted_at' => null,
      ],
    ];

    User::insert($users);
  }
}
